version: '3.8'

services:
  debugger-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    image: debugger-mcp:latest
    container_name: debugger-mcp-server
    
    # Mount workspace for debugging programs
    volumes:
      - ./workspace:/workspace
    
    # STDIO mode - interact via stdin/stdout
    stdin_open: true
    tty: true
    
    # Environment variables
    environment:
      - RUST_LOG=info
    
    # Restart policy
    restart: unless-stopped

  # Example: Run with specific log level
  debugger-mcp-debug:
    image: debugger-mcp:latest
    container_name: debugger-mcp-debug
    volumes:
      - ./workspace:/workspace
    stdin_open: true
    tty: true
    environment:
      - RUST_LOG=debug
    command: ["debugger_mcp", "serve", "--log-level", "debug"]
    profiles:
      - debug
