# cargo-nextest configuration for debugger-mcp
# Documentation: https://nexte.st/book/configuration.html

[profile.default]
# Number of retries for failed tests
retries = 0

# Test threads ("num-cpus" = number of logical CPUs)
test-threads = "num-cpus"

# Slow test timeout
slow-timeout = { period = "60s", terminate-after = 2 }

# Leak timeout
leak-timeout = "100ms"

[profile.ci]
# CI-specific configuration
# Fail fast to save CI time
fail-fast = false

# Retries for flaky tests in CI
retries = 2

# Stricter timeouts in CI
slow-timeout = { period = "30s", terminate-after = 1 }

# More detailed output
status-level = "all"
final-status-level = "all"

# Generate JUnit XML for CI systems
# (nextest can generate this natively)

[profile.default.junit]
path = "target/nextest/junit.xml"
